### ISSUE TITLE
[isthmus] conversion failures with SetRels

### ISSUE THREAD

**Issue by vbarua** [substrait-io/substrait-java#186]
Under certain conditions, attempting to convert a SetRel its Calcite equivalent results in the following error:
```
type mismatch:
ref:
INTEGER NOT NULL
input:
INTEGER
```

The reason this happens requires a bit of an explanation.

Calcite derives the row type for set operations using the code [here](https://github.com/apache/calcite/blob/e1991e08a225ef08c2402ab35c310d88fff3c222/core/src/main/java/org/apache/calcite/rel/core/SetOp.java#L115-L126). What this does is:
1. Compare the columns of each of the inputs to make sure they have the same type.
2. Set the nullability of each column to be the least restrictive of its inputs. For a given column index, if any of the inputs has that column as nullable, the final output columns is nullable.

Here is an example to illustrate this:
```
Input 1: (I64, I64, I64?, I64?)
Input 2: (I64, I64?, I64, I64?)
Output:  (I64, I64?, I64?, I64?)
```

Now, substrait-java arbitrarily sets the return type of a set operation to be a return type of the first input. See [here](https://github.com/substrait-io/substrait-java/blob/6e82f397a168f3811593fe8248753d70d4f0c04f/core/src/main/java/io/substrait/relation/Set.java#L41-L44).

This is the source of the disagreement between types, but actually not enough to trigger the issue. The final item needed is a FieldReference over the set operation. As describe in https://github.com/substrait-io/substrait-java/issues/185, the FieldReferences ends up storing the type derived by substrait-java. Converting this field reference can then fail, if the type it stores does not match up with the type derived by Calcite.

## Code Example
The following code reproduces the issue:
```java
  @ParameterizedTest
  @EnumSource(Set.SetOp.class)
  void setConversionFailurs(Set.SetOp op) {
    if (op.equals(Set.SetOp.UNKNOWN)) {
      return;
    }

    SubstraitBuilder b = new SubstraitBuilder(extensions);

    TypeCreator R = TypeCreator.of(false);
    TypeCreator N = TypeCreator.of(true);

    NamedScan primaryTable =
        b.namedScan(
            List.of("primary"), List.of("a", "b", "c", "d"), List.of(R.I32, R.I32, N.I32, N.I32));

    NamedScan secondaryTable =
        b.namedScan(
            List.of("secondary"), List.of("a", "b", "c", "d"), List.of(R.I32, N.I32, R.I32, N.I32));

    var plan =
        b.project(
            input ->
                List.of(
                    // using a field reference triggers a call to deriveRecordType
                    // this embeds the type derived from the Substrait Set in the POJO
                    // if this type does not match the type Calcite expects, an exception is thrown
                    b.fieldReference(input, 0),
                    b.fieldReference(input, 1),
                    b.fieldReference(input, 2),
                    b.fieldReference(input, 3)),
            b.remap(4, 5, 6, 7),
            b.set(op, primaryTable, secondaryTable));
    assertFullRoundTrip(plan);
  }
```

**Comment by vbarua** [comment]
I've created an issue in Calcite to potentially improve its type derivation.
https://issues.apache.org/jira/browse/CALCITE-6451

**Comment by nielspardon** [comment]
CALCITE-6451 ("Improve Nullability Derivation for Intersect and Minus") has been resolved and is slated for Calcite 1.43.0. It aligns Calcite's INTERSECT/MINUS output nullability derivation with what substrait-java already computes in `Set#deriveRecordType`, so the type disagreement described here should no longer occur once we bump to Calcite 1.43.0 (we currently target 1.42.0). We should be able to resolve this issue with that upgrade.

**Comment by alexandrefimov** [comment]
Re-ran the repro from the description on `4242051`. It still fails for all eight operations, but only half of that is the mismatch this issue is about, and the cause named above has moved.

`Set.deriveRecordType` is no longer "the return type of the first input". It splits by operation: `MINUS*` keeps the primary's types, `INTERSECTION*` coalesces column-wise toward non-nullable, `UNION*` toward nullable. Calcite derives every set operation's row type with `leastRestrictive`. So the two now agree for unions, and disagree exactly where Substrait's rule differs:

| operation | outcome on `4242051` |
| --- | --- |
| `MINUS_PRIMARY`, `MINUS_PRIMARY_ALL` | `type mismatch: ref INTEGER NOT NULL / input INTEGER` |
| `INTERSECTION_MULTISET`, `INTERSECTION_MULTISET_ALL` | same |
| `MINUS_MULTISET`, `INTERSECTION_PRIMARY` | `UnsupportedOperationException: Unsupported set operation` |
| `UNION_DISTINCT`, `UNION_ALL` | round trip loses the identity `Project` over the `Set`; the types agree |

For the repro's inputs -- primary `(i32, i32, i32?, i32?)`, secondary `(i32, i32?, i32, i32?)` -- `MINUS_PRIMARY` derives `(i32, i32, i32?, i32?)` where Calcite derives `(i32, i32?, i32?, i32?)`. Column `b` is where the `FieldReference` then claims `NOT NULL` over a nullable input.

Worth knowing for anyone reproducing it: the failure is assertion-gated, out of `Project.<init>` → `Project.isValid` → `RexChecker.visitInputRef` → `Litmus.THROW`. With `enableAssertions = false` those four cases pass and the round trip is clean -- so outside tests this is not an exception but a `RexInputRef` typed `NOT NULL` sitting over a nullable input, which is the state that would mislead a planner rule.

The last two rows are not a type disagreement at all -- `SubstraitRelNodeConverter.getRelBuilder` has no case for those two operations and falls through to `default` -- and that looks deliberate rather than missing. The spec at v0.101.0, which is what this tree is pinned to, says both `MINUS_MULTISET` and `INTERSECTION_PRIMARY` have no direct SQL mapping, while every operation that does have one is mapped: `MINUS_PRIMARY` to `EXCEPT DISTINCT`, `MINUS_PRIMARY_ALL` to `EXCEPT ALL`, `INTERSECTION_MULTISET` to `INTERSECT DISTINCT`. So the repro sweeps two operations a SQL-shaped target cannot express, and the mismatch this issue is about is the four rows above them.
