### ISSUE TITLE
SPECIFICATION_VERSION missing in manifest

### ISSUE THREAD

**Issue by vbarua** [substrait-io/substrait-java#411]
Following https://github.com/substrait-io/substrait-java/pull/406, @ingomueller-net reported issues when updating the consumer-testing library to use

See: https://github.com/substrait-io/substrait-java/commit/de8bf2abce302dadbcead2364f6f950fc5ad6673#r159771706

It may make sense to revert the changes before the next release.

**Comment by nielspardon** [comment]
@ingomueller-net can you share a bit more context about your build environment? are you experiencing this locally or in Github Actions?

**Comment by nielspardon** [comment]
Please still provide some reproduction steps just to be sure I'm looking at the right problem.

**Comment by nielspardon** [comment]
Good, then I think my PR will fix your issue.

**Comment by vbarua** [comment]
@ingomueller-net I've merged Niels' PR which should fix your issue hopefully. Let us know if it works (or doesn't).

**Comment by ingomueller-net** [comment]
Thanks a lot for taking care of this issue promptly! However, it doesn't seem to work yet; I still get the same error. A few things I observed:

* The manifest file is now in the jar and the specification version is set:
   ```
   $ jar -xf jars/isthmus-0.58.0-all.jar META-INF/MANIFEST.MF
   $ grep Specification META-INF/MANIFEST.MF 
   Specification-Title: substrait
   Specification-Version: 0.69.0
   ```
* I am not sure if that was the problem to begin with. [`getResourceAsStream`](https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#getResourceAsStream-java.lang.String-) returns `null` if no manifest file is found, so if that were the case, we should have gotten an `NullPointerException` on using the *manifest*, not on using the value looked up in the manifest. (It could be, it finds some other manifest though that I am not aware of...)
* [`getValue`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/jar/Attributes.html#getValue(java.util.jar.Attributes.Name)) on the manifest attributes returns `null` if the attribute wasn't found. That seems to be happening still. Maybe it'd be worth testing that and throwing an exception to improve the error message?

**Comment by nielspardon** [comment]
> * I am not sure if that was the problem to begin with. [`getResourceAsStream`](https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#getResourceAsStream-java.lang.String-) returns `null` if no manifest file is found, so if that were the case, we should have gotten an `NullPointerException` on using the _manifest_, not on using the value looked up in the manifest. (It could be, it finds some other manifest though that I am not aware of...)

ok, this is a bit strange but fine. we can try another workaround.

just FYI the way this is supposed to work is that when the Substrait Java core classes are packaged in a JAR they will never reach the code that uses `getResourceAsStream` but the first statement of the `loadVersion()` would have found the value already. The second part was just meant for the Gradle build when the compiled Java classes are not packaged in a JAR:

```
    private static String[] loadVersion() {
      // load the specification version from the JAR manifest
      String specificationVersion = Version.class.getPackage().getSpecificationVersion();


      // load the manifest directly from the classpath if the specification version is null which is
      // the case if the Version class is not in a JAR, e.g. during the Gradle build
      if (specificationVersion == null) {
        try {
          Manifest manifest =
              new Manifest(
                  Version.class.getClassLoader().getResourceAsStream("META-INF/MANIFEST.MF"));
          specificationVersion = manifest.getMainAttributes().getValue(Name.SPECIFICATION_VERSION);
        } catch (IOException e) {
          throw new IllegalStateException("Could not load version from manifest", e);
        }
      }


      return specificationVersion.split("\\.");
    }
  }
```

What we can do is that instead of using the `MANIFEST.MF` we simply create our own resource file and load that with `getResourceAsStream` all of the time.

**Comment by ingomueller-net** [comment]
OK, I understand. I can't really help with deciding what's best -- too little Java experience.

I have managed to do some debugging, though: interestingly, the manifest is found and the content I print is the expected one -- and includes the specification version. I am still in the process of finding out why the look-up doesn't work.

**Comment by ingomueller-net** [comment]
Interesting. It works on my machine now but not in CI. Still investigating...

**Comment by nielspardon** [comment]
> Interesting. It works on my machine now but not in CI. Still investigating...

on CI with Github actions the git submodule update action does not fetch the git tags for the submodule. we had to add an extra shell command to the Github actions config to fetch the tags explicitly:
https://github.com/substrait-io/substrait-java/blob/33c83dc2babb4114607333d8299eced88e4afa01/.github/workflows/pr.yml#L73-L74

**Comment by ingomueller-net** [comment]
Thanks a lot for the tip. That sounded promising and it may be required for us as well but there must be something else. This is the manifest I am getting:

```
Manifest-Version: 1.0
Premain-Class: org.jpype.agent.JPypeAgent
Created-By: 11.0.25 (Eclipse Adoptium)
```

Any idea where that could be coming from?

**Comment by nielspardon** [comment]
> Any idea where that could be coming from?

In the Java world every library is packaged as a JAR. Every JAR has it's own manifest. Since in the substrait-java/core code we are calling `Version.class.getPackage().getSpecificationVersion()` what happens is that Java discovers the manifest of the JAR in which the `Version` class is packaged if it is packaged in a JAR. The `isthmus-all.jar` shadow JAR you are using in consumer testing merges all the compiled java classes (including the Version class) and other files (extension yamls) into one big JAR and adds a new manifest for this new uber-jar. What my fix does is that I ensure that the manifest of the uber-jar also has the specification-version entry so that when `Version.class.getPackage().getSpecificationVersion()` gets called Java looks up the specification version from the manifest of the JAR where the `Version` class resides which is no longer the `core.jar` but now the `isthmus-all.jar`.

`getResourceAsStream` allows you to discover files by name which are on the classpath. If there are multiple files on the classpath with the same name then they override each other and you end up with the one that won.

You might be getting the JPype manifest if you are testing with `getResourceAsStream` because that one won and does not necessarily mean something is wrong. Running `Version.class.getPackage().getSpecificationVersion()` from Python through JPype might be the more accurate test to see if it generally works.

Since you said earlier it locally works but does not work on CI this signaled to me that there must be something different on the CI environment vs your local environment. I did yesterday clone the consumer-testing repo following the steps in the readme and also ran the build shell script locally. I noticed that my local git clone did have the Git tags for the `substrait-java/substrait` git submodule which would explain why it is not a problem for you locally. That's why my next guess was (also on previous experience with the substrait-java repo) that the Git tags might be missing on the CI system.

**Comment by nielspardon** [comment]
Can you try changing this: https://github.com/substrait-io/consumer-testing/blob/8db192aa5dbda75f2df134ca1a55d6bb9217404e/.github/workflows/test.yml#L67-L70

```diff
    - name: Build Isthmus
      if: ${{ matrix.producer == 'isthmus' }}
      working-directory: ./substrait-java/isthmus
-      run: ../gradlew shadowJar
+      run: |
+         # fetch submodule tags since actions/checkout@v4 does not 
+         git submodule foreach 'git fetch --unshallow || true' 
+
+         ../gradlew shadowJar
```

**Comment by ingomueller-net** [comment]
> You can also try the following since `Version` and `Plan` are in the same JAR:

Yep, that gets me a bit further, but now I [get](https://github.com/substrait-io/consumer-testing/actions/runs/15611377638/job/43972862685?pr=246) the same error as initially: `NullPointerException` on `specificationVersion` as soon as I load the `Plan` class from JPype. This is because the manifest is still [this one](https://github.com/substrait-io/substrait-java/issues/411#issuecomment-2966335955).

**Comment by ingomueller-net** [comment]
I am giving up for the time being. This seems to be some weird Java problem, for which I don't have enough background. Let me know if you need help from my side.

**Comment by nielspardon** [comment]
oh, you need approve every new commit. that might be a bit annoying for you. is there a way around this?

**Comment by nielspardon** [comment]
It's pretty strange. I'm going to continue tomorrow. I have a couple of options. It's almost as if the Python Java bridge JPype is causing some weird behavior in both the `getResourceAsStream` and the `getPackaget().getSpecificationVersion()` scenarios.

**Comment by nielspardon** [comment]
I was able to update the pytest snapshots and now the build runs fully through for me.

created this PR for the substrait-java changes: https://github.com/substrait-io/substrait-java/pull/416
